### ISSUE TITLE
Add logo for OSMbe/State of the map

### ISSUE THREAD

**Issue by joostschouppe** [OSGeo-be/foss4g.be#37]
Could a logo like this be added below the current logo?

![State of the Map Belgium](https://user-images.githubusercontent.com/10122639/196045786-cd2bd580-0dd2-4c3b-ab52-b4ac1eb120a9.png)

I know SVG is better, but I couldn't get Inkscape to do something decent. The original OSMbe logo is at https://github.com/osmbe/presentations/blob/master/design/logo.svg if anyone wants to do something better

**Comment by joostschouppe** [comment]
Hey, turns out I can export from Canva to SVG. Here's the SVG version:
![State of the Map Belgium](https://user-images.githubusercontent.com/10122639/196119659-2b0bdcb4-cd59-4c97-94d4-c29dcaf13ed9.svg)

**Comment by marcu** [comment]
I try to adapt the logo. But it doesn't work as expected :/
