### ISSUE TITLE
OSMbe sponsors for the sponsors page

### ISSUE THREAD

**Issue by joostschouppe** [OSGeo-be/foss4g.be#39]
Just something like:

The Corporate Members of OpenStreetMap Belgium make this event possible. Thank you to Geo-6, Anyways, Champs-Libres (also Brons sponsor), Visit Flanders, RouteYou, TomTom and Mapbox (also Gold Sponsor)!

De Corporate Members van OpenStreetMap Belgium maken dit event mee mogelijk. Bedankt aan Geo-6, Anyways, Champs-Libres (ook Bronze sponsor), Visit Flanders, RouteYou, TomTom and Mapbox (ook Gold sponsor)!

**Comment by marcu** [comment]
I update the sponsors page. Is it ok for you ?

If you want we can put the "Corporate Members of OpenStreetMap Belgium" paragraph upper or bigger. What do you think ?

**Comment by joostschouppe** [comment]
This is perfect! Thanks!
