### ISSUE TITLE
www.foss4g.be does not work

### ISSUE THREAD

**Issue by jbelien** [OSGeo-be/foss4g.be#4]
I saw on the `README.md` you mention http://www.foss4g.be/ but it does not work !

http://foss4g.be/ is correctly redirected to https://2018.foss4g.be/ but not the `www`.

**Comment by johanvdw** [comment]
I'll have a look - I just updated the dns settings.

**Comment by jbelien** [comment]
Works now !
But redirects to http://2017.foss4g.be/

**Comment by johanvdw** [comment]
I noticed, and I don't understand why :-)

**Comment by jbelien** [comment]
Redirection is fixed ! :)
